### ISSUE TITLE
GreengrassLogMessage: add raw json config option for the 'message' field

### ISSUE THREAD

**Issue by jacques-dau** [aws-greengrass/aws-greengrass-logging-java#175]
**Feature Description**
Add a configuration item in order to enable a  raw json string in the GreengrassLogMessage 'message' field.

**Use Case**
I am deploying the greengrass Nucleus on my iot devices and configuring the Nucleus to output logs in JSON format. I would also like to utilize JSON format logs for my private components managed by the Nucleus. Currently my component JSON log messages logged to stdout are captured by the Nucleus component and are written in the Nucleus JSON log format BUT with my JSON log escaped with quotes. 

I would like my component logs to be presented as raw JSON format. 

This also further increase the value when exporting the logs to cloudwatch. Cloudwatch supports JSON logs and extract fields when using log insights, or when viewing the logtrails.

Without the raw JSON log. My component logs are just an escaped string in cloudwatch.

example of MY component log line:
```
{"time":1686816421,"level":"INFO","source":{"function":"client.(*Client).handleResponse","file":"client.go","line":123},"msg":"/get/accepted"}
```
example of the current Nucleus log line:
```
{"thread":"Copier","level":"INFO","eventType":"stdout","message":"{\"time\":1686816421,\"level\":\"INFO\",\"source\":{\"function\":\"client.(*Client).handleResponse\",\"file\":\"client.go\",\"line\":123},\"msg\":\"/get/accepted\"}","contexts":{"scriptName":"mycomponent.lifecycle.Run.Script","serviceName":"mycomponent","currentState":"RUNNING"},"loggerName":"mycomponent","timestamp":1686816421138,"cause":null}
```

example of the proposed log line when 'raw json' configuration enabled:
```
{"thread":"Copier","level":"INFO","eventType":"stdout","message": {"time":1686816421,"level":"INFO","source":{"function":"client.(*Client).handleResponse","file":"client.go","line":123},"msg":"/get/accepted"},"contexts":{"scriptName":"mycomponent.lifecycle.Run.Script","serviceName":"mycomponent","currentState":"RUNNING"},"loggerName":"mycomponent","timestamp":1686816421138,"cause":null}

```

**Proposed Solution**
Add a configuration option in order to support raw json messages.

**Other**
Example how to enable a raw json string message:
https://stackoverflow.com/questions/4783421/how-can-i-include-raw-json-in-an-object-using-jackson

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hello @jacques-dau,

Thank you for your suggestion. I'd recommend that you use your own logger, such as Log4J and output to a log file which you own if you want to customize the behavior. In this way, you have full control over what the logs look like.

**Comment by MikeDombo** [comment]
It is when you want something more specific, yes. You're saying that our behavior isn't what you want, so in this case you can write your own files to achieve that behavior.

**Comment by jacques-dau** [comment]
Thanks for the quick response.
